/* This file was generated by syncqt. */
#ifndef QT_QTUITOOLS_VERSION_H
#define QT_QTUITOOLS_VERSION_H

#define QTUITOOLS_VERSION_STR "6.11.1"

#define QTUITOOLS_VERSION 0x0601101

#endif // QT_QTUITOOLS_VERSION_H
