QT.multimedia_private.VERSION = 6.11.1
QT.multimedia_private.name = QtMultimedia
QT.multimedia_private.module =
QT.multimedia_private.libs = $$QT_MODULE_LIB_BASE
QT.multimedia_private.includes = $$QT_MODULE_INCLUDE_BASE/QtMultimedia/6.11.1 $$QT_MODULE_INCLUDE_BASE/QtMultimedia/6.11.1/QtMultimedia
QT.multimedia_private.frameworks = 
QT.multimedia_private.depends = core_private gui_private multimedia
QT.multimedia_private.uses = 
QT.multimedia_private.module_config = v2 internal_module
QT.multimedia_private.enabled_features = pipewire pipewire_screencapture linux_v4l linux_dmabuf vaapi pulseaudio spatialaudio spatialaudio_quick3d ffmpeg ffmpeg_stubs
QT.multimedia_private.disabled_features = alsa avfoundation coreaudio videotoolbox gstreamer gstreamer_photography gstreamer_gl gstreamer_gl_wayland gstreamer_gl_egl gstreamer_gl_x11 gpu_vivante mmrenderer native_android_backend native_windows_backend aaudio wasm wasapi
QMAKE_LIBS_ALSA = -lasound
QMAKE_INCDIR_GSTREAMER_1_0 = /usr/include/gstreamer-1.0 /usr/include/glib-2.0 /usr/lib64/glib-2.0/include /usr/include/sysprof-4 /usr/include/orc-0.4
QMAKE_LIBS_GSTREAMER_1_0 = -lglib-2.0 -lgobject-2.0 -lgstreamer-1.0 -lgstallocators-1.0 -lglib-2.0 -lgobject-2.0 -lgstreamer-1.0 -lgstbase-1.0 -lgstaudio-1.0 -lgstvideo-1.0 -lgstpbutils-1.0 -lglib-2.0 -lgobject-2.0 -lgstreamer-1.0 -lgstbase-1.0 -lgstvideo-1.0 -lglib-2.0 -lgobject-2.0 -lgstreamer-1.0 -lgstbase-1.0 -lgstaudio-1.0 -lglib-2.0 -lgobject-2.0 -lgstreamer-1.0 -lgstbase-1.0 -lglib-2.0 -lgobject-2.0 -lgstreamer-1.0
QMAKE_INCDIR_GSTREAMER_APP_1_0 = /usr/include/gstreamer-1.0 /usr/include/glib-2.0 /usr/lib64/glib-2.0/include /usr/include/sysprof-4
QMAKE_LIBS_GSTREAMER_APP_1_0 = -lglib-2.0 -lgobject-2.0 -lgstreamer-1.0 -lgstbase-1.0 -lgstapp-1.0
QMAKE_LIBS_GSTREAMER_PHOTOGRAPHY_1_0 = 
QMAKE_INCDIR_GSTREAMER_GL_1_0 = /usr/include/gstreamer-1.0 /usr/lib64/gstreamer-1.0/include /usr/include/glib-2.0 /usr/lib64/glib-2.0/include /usr/include/sysprof-4 /usr/include/orc-0.4 /usr/include/gudev-1.0 /usr/include/libdrm /usr/include/valgrind
QMAKE_LIBS_GSTREAMER_GL_1_0 = -lglib-2.0 -lgobject-2.0 -lgstreamer-1.0 -lgstbase-1.0 -lgstvideo-1.0 -lgstgl-1.0
QMAKE_INCDIR_GSTREAMER_GL_WAYLAND_1_0 = /usr/include/gstreamer-1.0 /usr/lib64/gstreamer-1.0/include /usr/include/glib-2.0 /usr/lib64/glib-2.0/include /usr/include/sysprof-4 /usr/include/orc-0.4 /usr/include/gudev-1.0 /usr/include/libdrm /usr/include/valgrind
QMAKE_LIBS_GSTREAMER_GL_WAYLAND_1_0 = -lwayland-client -lwayland-egl -lglib-2.0 -lgobject-2.0 -lgstreamer-1.0 -lgstbase-1.0 -lgstvideo-1.0 -lgstgl-1.0
QMAKE_INCDIR_GSTREAMER_GL_EGL_1_0 = /usr/include/gstreamer-1.0 /usr/lib64/gstreamer-1.0/include /usr/include/glib-2.0 /usr/lib64/glib-2.0/include /usr/include/sysprof-4 /usr/include/orc-0.4 /usr/include/gudev-1.0 /usr/include/libdrm /usr/include/valgrind
QMAKE_LIBS_GSTREAMER_GL_EGL_1_0 = -lEGL -lglib-2.0 -lgobject-2.0 -lgstreamer-1.0 -lgstbase-1.0 -lgstvideo-1.0 -lgstgl-1.0
QMAKE_INCDIR_GSTREAMER_GL_X11_1_0 = /usr/include/gstreamer-1.0 /usr/lib64/gstreamer-1.0/include /usr/include/glib-2.0 /usr/lib64/glib-2.0/include /usr/include/sysprof-4 /usr/include/orc-0.4 /usr/include/gudev-1.0 /usr/include/libdrm /usr/include/valgrind
QMAKE_LIBS_GSTREAMER_GL_X11_1_0 = -lxcb -lX11 -lX11-xcb -lglib-2.0 -lgobject-2.0 -lgstreamer-1.0 -lgstbase-1.0 -lgstvideo-1.0 -lgstgl-1.0
QMAKE_LIBS_PULSEAUDIO = -lpulse
QMAKE_LIBDIR_FFMPEG = /usr/local/FFmpeg-n7.1.3/lib
QMAKE_INCDIR_FFMPEG = /usr/local/FFmpeg-n7.1.3/include
QMAKE_LIBS_FFMPEG = -lswscale -lswresample -lavutil -lavformat -lavcodec
QMAKE_INCDIR_PIPEWIRE = /usr/include/pipewire-0.3 /usr/include/spa-0.2
QMAKE_LIBS_PIPEWIRE = -lpipewire-0.3
QMAKE_LIBS_VAAPI = -lva -lva-drm -lva
