QT.quick_private.VERSION = 6.11.1
QT.quick_private.name = QtQuick
QT.quick_private.module =
QT.quick_private.libs = $$QT_MODULE_LIB_BASE
QT.quick_private.includes = $$QT_MODULE_INCLUDE_BASE/QtQuick/6.11.1 $$QT_MODULE_INCLUDE_BASE/QtQuick/6.11.1/QtQuick
QT.quick_private.frameworks = 
QT.quick_private.depends = core_private gui_private qmlmodels_private qml_private qmlmeta_private quick core_private gui_private qml_private
QT.quick_private.uses = 
QT.quick_private.module_config = v2 internal_module
QT.quick_private.enabled_features = quick-animatedimage quick-canvas quick-designer quick-dialogs quick-flipable quick-gridview quick-itemview quick-viewtransitions quick-listview quick-tableview quick-treeview quick-particles quick-path quick-pathview quick-positioners quick-repeater quick-sprite quick-vectorimage
QT.quick_private.disabled_features = 
